In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [5]:
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep, dep, test_size=0.30, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
from sklearn.preprocessing import StandardScaler 
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [9]:
preinput_data=[[35,30,1,0,0]]

In [10]:
preinput=sc.transform(preinput_data)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [11]:
preinput

array([[-0.31925224, -0.12072137, -0.06746417, -0.97676557, -0.50466988]])

In [13]:
import pickle
loaded_model=pickle.load(open("model_RF_PreInputOutput_without_pkl_file.sav",'rb'))      
result=loaded_model.predict(preinput)

In [14]:
result

array([-0.63821497])

In [15]:
preoutput=scy.inverse_transform([result])

In [16]:
preoutput

array([[5654.9035212]])